services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: wget -q --spider http://localhost:8878/healthcheck || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "${SERVER_PORT}:8878"
